//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USite.Presentation.Ressources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Ressources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Ressources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("USite.Presentation.Ressources.Ressources", typeof(Ressources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have access to this resource..
        /// </summary>
        public static string AccessDenied_message {
            get {
                return ResourceManager.GetString("AccessDenied_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access denied.
        /// </summary>
        public static string AccessDenied_title {
            get {
                return ResourceManager.GetString("AccessDenied_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USite.
        /// </summary>
        public static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured during the confirmation of your email, try again later..
        /// </summary>
        public static string ConfirmMail_error {
            get {
                return ResourceManager.GetString("ConfirmMail_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your email is confirmed, you can use the application..
        /// </summary>
        public static string ConfirmMail_success {
            get {
                return ResourceManager.GetString("ConfirmMail_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm email.
        /// </summary>
        public static string ConfirmMail_title {
            get {
                return ResourceManager.GetString("ConfirmMail_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm email change.
        /// </summary>
        public static string ConfirmMailChange_title {
            get {
                return ResourceManager.GetString("ConfirmMailChange_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while processing your request..
        /// </summary>
        public static string Error_Message {
            get {
                return ResourceManager.GetString("Error_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request ID:.
        /// </summary>
        public static string Error_RequestId {
            get {
                return ResourceManager.GetString("Error_RequestId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error_Title {
            get {
                return ResourceManager.GetString("Error_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve successfully authenticated with.
        /// </summary>
        public static string ExternalLogin_Message1 {
            get {
                return ResourceManager.GetString("ExternalLogin_Message1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter some extra information for complete your account and click the register button to finish logging in..
        /// </summary>
        public static string ExternalLogin_Message2 {
            get {
                return ResourceManager.GetString("ExternalLogin_Message2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password.
        /// </summary>
        public static string ForgotPassword_BtnResetPassword {
            get {
                return ResourceManager.GetString("ForgotPassword_BtnResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your password?.
        /// </summary>
        public static string ForgotPassword_Title {
            get {
                return ResourceManager.GetString("ForgotPassword_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your email..
        /// </summary>
        public static string ForgotPassword_Title2 {
            get {
                return ResourceManager.GetString("ForgotPassword_Title2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your email to reset your password..
        /// </summary>
        public static string ForgotPasswordConfirmation_Message {
            get {
                return ResourceManager.GetString("ForgotPasswordConfirmation_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot password confirmation.
        /// </summary>
        public static string ForgotPasswordConfirmation_Title {
            get {
                return ResourceManager.GetString("ForgotPasswordConfirmation_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string Index_Title {
            get {
                return ResourceManager.GetString("Index_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This account has been locked out, please try again later..
        /// </summary>
        public static string Lockout_Message {
            get {
                return ResourceManager.GetString("Lockout_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locked out.
        /// </summary>
        public static string Lockout_Title {
            get {
                return ResourceManager.GetString("Lockout_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in with.
        /// </summary>
        public static string Login_BtnExternalLogin {
            get {
                return ResourceManager.GetString("Login_BtnExternalLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your password?.
        /// </summary>
        public static string Login_LinkForgotPassword {
            get {
                return ResourceManager.GetString("Login_LinkForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register as a new user.
        /// </summary>
        public static string Login_LinkRegister {
            get {
                return ResourceManager.GetString("Login_LinkRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resend email confirmation.
        /// </summary>
        public static string Login_LinkResendMail {
            get {
                return ResourceManager.GetString("Login_LinkResendMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your login is protected with an authenticator app. Enter your authenticator code below..
        /// </summary>
        public static string LoginWith2fa_Message1 {
            get {
                return ResourceManager.GetString("LoginWith2fa_Message1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t have access to your authenticator device? You can.
        /// </summary>
        public static string LoginWith2fa_Message2 {
            get {
                return ResourceManager.GetString("LoginWith2fa_Message2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to log in with a
        ///            recovery code.
        /// </summary>
        public static string LoginWith2fa_Message3 {
            get {
                return ResourceManager.GetString("LoginWith2fa_Message3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two-factor authentication.
        /// </summary>
        public static string LoginWith2fa_Title {
            get {
                return ResourceManager.GetString("LoginWith2fa_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have requested to log in with a recovery code. This login will not be remembered until you provide an authenticator app code at log in or disable 2FA and log in again..
        /// </summary>
        public static string LoginWithRecoveryCode_Message {
            get {
                return ResourceManager.GetString("LoginWithRecoveryCode_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recovery code verification.
        /// </summary>
        public static string LoginWithRecoveryCode_Title {
            get {
                return ResourceManager.GetString("LoginWithRecoveryCode_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update password.
        /// </summary>
        public static string Manage_ChangePassword_BtnUpdate {
            get {
                return ResourceManager.GetString("Manage_ChangePassword_BtnUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        public static string Manage_ChangePassword_Title {
            get {
                return ResourceManager.GetString("Manage_ChangePassword_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete data and close my account.
        /// </summary>
        public static string Manage_DeletePersonalData_BtnDelete {
            get {
                return ResourceManager.GetString("Manage_DeletePersonalData_BtnDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting this data will permanently remove your account, and this cannot be recovered..
        /// </summary>
        public static string Manage_DeletePersonalData_Message {
            get {
                return ResourceManager.GetString("Manage_DeletePersonalData_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Personal Data.
        /// </summary>
        public static string Manage_DeletePersonalData_Title {
            get {
                return ResourceManager.GetString("Manage_DeletePersonalData_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable 2FA.
        /// </summary>
        public static string Manage_Disable2fa_Btn {
            get {
                return ResourceManager.GetString("Manage_Disable2fa_Btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This action only disables 2FA..
        /// </summary>
        public static string Manage_Disable2fa_Message1 {
            get {
                return ResourceManager.GetString("Manage_Disable2fa_Message1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabling 2FA does not change the keys used in authenticator apps. If you wish to change the key
        ///            used in an authenticator app you should.
        /// </summary>
        public static string Manage_Disable2fa_Message2 {
            get {
                return ResourceManager.GetString("Manage_Disable2fa_Message2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reset your authenticator
        ///                keys..
        /// </summary>
        public static string Manage_Disable2fa_Message3 {
            get {
                return ResourceManager.GetString("Manage_Disable2fa_Message3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable two-factor authentication (2FA).
        /// </summary>
        public static string Manage_Disable2fa_Title {
            get {
                return ResourceManager.GetString("Manage_Disable2fa_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Your Data.
        /// </summary>
        public static string Manage_DownloadPersonalData_Title {
            get {
                return ResourceManager.GetString("Manage_DownloadPersonalData_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify.
        /// </summary>
        public static string Manage_EnableAuthenticator_BtnVerif {
            get {
                return ResourceManager.GetString("Manage_EnableAuthenticator_BtnVerif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Android.
        /// </summary>
        public static string Manage_EnableAuthenticator_LinkAndroid {
            get {
                return ResourceManager.GetString("Manage_EnableAuthenticator_LinkAndroid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IOS
        ///.
        /// </summary>
        public static string Manage_EnableAuthenticator_LinkIos {
            get {
                return ResourceManager.GetString("Manage_EnableAuthenticator_LinkIos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To use an authenticator app go through the following steps:.
        /// </summary>
        public static string Manage_EnableAuthenticator_Message1 {
            get {
                return ResourceManager.GetString("Manage_EnableAuthenticator_Message1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download a two-factor authenticator app like Microsoft Authenticator for.
        /// </summary>
        public static string Manage_EnableAuthenticator_Message2 {
            get {
                return ResourceManager.GetString("Manage_EnableAuthenticator_Message2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan the QR Code or enter this key.
        /// </summary>
        public static string Manage_EnableAuthenticator_Message3 {
            get {
                return ResourceManager.GetString("Manage_EnableAuthenticator_Message3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to into your two factor authenticator app.
        ///                Spaces and casing do not matter..
        /// </summary>
        public static string Manage_EnableAuthenticator_Message4 {
            get {
                return ResourceManager.GetString("Manage_EnableAuthenticator_Message4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Once you have scanned the QR code or input the key above, your two factor authentication app will
        ///                provide you
        ///                with a unique code. Enter the code in the confirmation box below..
        /// </summary>
        public static string Manage_EnableAuthenticator_Message5 {
            get {
                return ResourceManager.GetString("Manage_EnableAuthenticator_Message5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google Authenticator for.
        /// </summary>
        public static string Manage_EnableAuthenticator_TextGoogle {
            get {
                return ResourceManager.GetString("Manage_EnableAuthenticator_TextGoogle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure authenticator app.
        /// </summary>
        public static string Manage_EnableAuthenticator_Title {
            get {
                return ResourceManager.GetString("Manage_EnableAuthenticator_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification Code.
        /// </summary>
        public static string Manage_EnableAuthenticator_VerifCode {
            get {
                return ResourceManager.GetString("Manage_EnableAuthenticator_VerifCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Manage_ExternalLogins_BtnRemove {
            get {
                return ResourceManager.GetString("Manage_ExternalLogins_BtnRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in using your.
        /// </summary>
        public static string Manage_ExternalLogins_MessageLog1 {
            get {
                return ResourceManager.GetString("Manage_ExternalLogins_MessageLog1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to account.
        /// </summary>
        public static string Manage_ExternalLogins_MessageLog2 {
            get {
                return ResourceManager.GetString("Manage_ExternalLogins_MessageLog2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove this.
        /// </summary>
        public static string Manage_ExternalLogins_MessageRemove1 {
            get {
                return ResourceManager.GetString("Manage_ExternalLogins_MessageRemove1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to login from your account.
        /// </summary>
        public static string Manage_ExternalLogins_MessageRemove2 {
            get {
                return ResourceManager.GetString("Manage_ExternalLogins_MessageRemove2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage your external logins.
        /// </summary>
        public static string Manage_ExternalLogins_Title {
            get {
                return ResourceManager.GetString("Manage_ExternalLogins_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Recovery Codes.
        /// </summary>
        public static string Manage_GenerateRecoveryCodes_BtnRecovery {
            get {
                return ResourceManager.GetString("Manage_GenerateRecoveryCodes_BtnRecovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Put these codes in a safe place..
        /// </summary>
        public static string Manage_GenerateRecoveryCodes_Message1 {
            get {
                return ResourceManager.GetString("Manage_GenerateRecoveryCodes_Message1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you lose your device and don&apos;t have the recovery codes you will lose access to your account..
        /// </summary>
        public static string Manage_GenerateRecoveryCodes_Message2 {
            get {
                return ResourceManager.GetString("Manage_GenerateRecoveryCodes_Message2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generating new recovery codes does not change the keys used in authenticator apps. If you wish to change the key
        ///            used in an authenticator app you should.
        /// </summary>
        public static string Manage_GenerateRecoveryCodes_Message3 {
            get {
                return ResourceManager.GetString("Manage_GenerateRecoveryCodes_Message3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reset your authenticator keys..
        /// </summary>
        public static string Manage_GenerateRecoveryCodes_MessageLink {
            get {
                return ResourceManager.GetString("Manage_GenerateRecoveryCodes_MessageLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate two-factor authentication (2FA) recovery codes.
        /// </summary>
        public static string Manage_GenerateRecoveryCodes_Title {
            get {
                return ResourceManager.GetString("Manage_GenerateRecoveryCodes_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Manage_Index_BtnSave {
            get {
                return ResourceManager.GetString("Manage_Index_BtnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage your account.
        /// </summary>
        public static string Manage_Layout_Title1 {
            get {
                return ResourceManager.GetString("Manage_Layout_Title1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change your account settings.
        /// </summary>
        public static string Manage_Layout_Title2 {
            get {
                return ResourceManager.GetString("Manage_Layout_Title2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change email.
        /// </summary>
        public static string Manage_Mail_BtnChangeEmail {
            get {
                return ResourceManager.GetString("Manage_Mail_BtnChangeEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send verification email.
        /// </summary>
        public static string Manage_Mail_BtnVerification {
            get {
                return ResourceManager.GetString("Manage_Mail_BtnVerification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Email.
        /// </summary>
        public static string Manage_Mail_Title {
            get {
                return ResourceManager.GetString("Manage_Mail_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External logins.
        /// </summary>
        public static string Manage_Nav_External {
            get {
                return ResourceManager.GetString("Manage_Nav_External", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal data.
        /// </summary>
        public static string Manage_Nav_Personal {
            get {
                return ResourceManager.GetString("Manage_Nav_Personal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two-factor authentication.
        /// </summary>
        public static string Manage_Nav_TwoFactor {
            get {
                return ResourceManager.GetString("Manage_Nav_TwoFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Manage_PersonalData_BtnDelete {
            get {
                return ResourceManager.GetString("Manage_PersonalData_BtnDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string Manage_PersonalData_BtnDownload {
            get {
                return ResourceManager.GetString("Manage_PersonalData_BtnDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting this data will permanently remove your account, and this cannot be recovered..
        /// </summary>
        public static string Manage_PersonalData_Message1 {
            get {
                return ResourceManager.GetString("Manage_PersonalData_Message1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account contains personal data that you have given us. This page allows you to download or delete that data..
        /// </summary>
        public static string Manage_PersonalData_Message2 {
            get {
                return ResourceManager.GetString("Manage_PersonalData_Message2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Data.
        /// </summary>
        public static string Manage_PersonalData_Title {
            get {
                return ResourceManager.GetString("Manage_PersonalData_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset authenticator key.
        /// </summary>
        public static string Manage_ResetAuthenticator_BtnResetAuthenticator {
            get {
                return ResourceManager.GetString("Manage_ResetAuthenticator_BtnResetAuthenticator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you reset your authenticator key your authenticator app will not work until you reconfigure
        ///        it..
        /// </summary>
        public static string Manage_ResetAuthenticator_Message1 {
            get {
                return ResourceManager.GetString("Manage_ResetAuthenticator_Message1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This process disables 2FA until you verify your authenticator app.
        ///        If you do not complete your authenticator app configuration you may lose access to your account..
        /// </summary>
        public static string Manage_ResetAuthenticator_Message2 {
            get {
                return ResourceManager.GetString("Manage_ResetAuthenticator_Message2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset authenticator key.
        /// </summary>
        public static string Manage_ResetAuthenticator_Title {
            get {
                return ResourceManager.GetString("Manage_ResetAuthenticator_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have a local username/password for this site. Add a local
        ///        account so you can log in without an external login..
        /// </summary>
        public static string Manage_SetPassword_Message {
            get {
                return ResourceManager.GetString("Manage_SetPassword_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set password.
        /// </summary>
        public static string Manage_SetPassword_Title {
            get {
                return ResourceManager.GetString("Manage_SetPassword_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set your password.
        /// </summary>
        public static string Manage_SetPassword_Title2 {
            get {
                return ResourceManager.GetString("Manage_SetPassword_Title2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Put these codes in a safe place..
        /// </summary>
        public static string Manage_ShowRecoveryCodes_Message1 {
            get {
                return ResourceManager.GetString("Manage_ShowRecoveryCodes_Message1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you lose your device and don&apos;t have the recovery codes you will lose access to your account..
        /// </summary>
        public static string Manage_ShowRecoveryCodes_Message2 {
            get {
                return ResourceManager.GetString("Manage_ShowRecoveryCodes_Message2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recovery codes.
        /// </summary>
        public static string Manage_ShowRecoveryCodes_Title {
            get {
                return ResourceManager.GetString("Manage_ShowRecoveryCodes_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forget this browser.
        /// </summary>
        public static string Manage_TwoFactorAuthentication_BtnForgetBrowser {
            get {
                return ResourceManager.GetString("Manage_TwoFactorAuthentication_BtnForgetBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add authenticator app.
        /// </summary>
        public static string Manage_TwoFactorAuthentication_LinkAddAuthenticator {
            get {
                return ResourceManager.GetString("Manage_TwoFactorAuthentication_LinkAddAuthenticator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable 2FA.
        /// </summary>
        public static string Manage_TwoFactorAuthentication_LinkDisable2FA {
            get {
                return ResourceManager.GetString("Manage_TwoFactorAuthentication_LinkDisable2FA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset authenticator app.
        /// </summary>
        public static string Manage_TwoFactorAuthentication_LinkResetAuthenticator {
            get {
                return ResourceManager.GetString("Manage_TwoFactorAuthentication_LinkResetAuthenticator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset recovery codes.
        /// </summary>
        public static string Manage_TwoFactorAuthentication_LinkResetRecoveryCode {
            get {
                return ResourceManager.GetString("Manage_TwoFactorAuthentication_LinkResetRecoveryCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set up authenticator app.
        /// </summary>
        public static string Manage_TwoFactorAuthentication_LinkSetAuthenticator {
            get {
                return ResourceManager.GetString("Manage_TwoFactorAuthentication_LinkSetAuthenticator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no recovery codes left..
        /// </summary>
        public static string Manage_TwoFactorAuthentication_Message1 {
            get {
                return ResourceManager.GetString("Manage_TwoFactorAuthentication_Message1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must accept the policy before you can enable two factor authentication..
        /// </summary>
        public static string Manage_TwoFactorAuthentication_Message10 {
            get {
                return ResourceManager.GetString("Manage_TwoFactorAuthentication_Message10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must.
        /// </summary>
        public static string Manage_TwoFactorAuthentication_Message2 {
            get {
                return ResourceManager.GetString("Manage_TwoFactorAuthentication_Message2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to before you can log in
        ///                            with a recovery code..
        /// </summary>
        public static string Manage_TwoFactorAuthentication_Message3 {
            get {
                return ResourceManager.GetString("Manage_TwoFactorAuthentication_Message3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have 1 recovery code left..
        /// </summary>
        public static string Manage_TwoFactorAuthentication_Message4 {
            get {
                return ResourceManager.GetString("Manage_TwoFactorAuthentication_Message4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can.
        /// </summary>
        public static string Manage_TwoFactorAuthentication_Message5 {
            get {
                return ResourceManager.GetString("Manage_TwoFactorAuthentication_Message5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have.
        /// </summary>
        public static string Manage_TwoFactorAuthentication_Message6 {
            get {
                return ResourceManager.GetString("Manage_TwoFactorAuthentication_Message6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to recovery codes left..
        /// </summary>
        public static string Manage_TwoFactorAuthentication_Message7 {
            get {
                return ResourceManager.GetString("Manage_TwoFactorAuthentication_Message7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You should.
        /// </summary>
        public static string Manage_TwoFactorAuthentication_Message8 {
            get {
                return ResourceManager.GetString("Manage_TwoFactorAuthentication_Message8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy and cookie policy have not been accepted..
        /// </summary>
        public static string Manage_TwoFactorAuthentication_Message9 {
            get {
                return ResourceManager.GetString("Manage_TwoFactorAuthentication_Message9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to generate a new set of recovery codes.
        /// </summary>
        public static string Manage_TwoFactorAuthentication_MessageRecoveryCodes {
            get {
                return ResourceManager.GetString("Manage_TwoFactorAuthentication_MessageRecoveryCodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two-factor authentication (2FA).
        /// </summary>
        public static string Manage_TwoFactorAuthentication_Title {
            get {
                return ResourceManager.GetString("Manage_TwoFactorAuthentication_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your email to confirm your account..
        /// </summary>
        public static string RegisterConfirmation_Message {
            get {
                return ResourceManager.GetString("RegisterConfirmation_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your email is confirmed. Go to your.
        /// </summary>
        public static string RegisterConfirmation_Message2 {
            get {
                return ResourceManager.GetString("RegisterConfirmation_Message2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register confirmation.
        /// </summary>
        public static string RegisterConfirmation_Title {
            get {
                return ResourceManager.GetString("RegisterConfirmation_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification email sent. Please check your email..
        /// </summary>
        public static string ResendMailConfirmation_Message {
            get {
                return ResourceManager.GetString("ResendMailConfirmation_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resend.
        /// </summary>
        public static string ResendMailConfirmation_Resend {
            get {
                return ResourceManager.GetString("ResendMailConfirmation_Resend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resend email confirmation.
        /// </summary>
        public static string ResendMailConfirmation_Title {
            get {
                return ResourceManager.GetString("ResendMailConfirmation_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your email..
        /// </summary>
        public static string ResendMailConfirmation_Title2 {
            get {
                return ResourceManager.GetString("ResendMailConfirmation_Title2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string ResetPassword_Reset {
            get {
                return ResourceManager.GetString("ResetPassword_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password.
        /// </summary>
        public static string ResetPassword_Title {
            get {
                return ResourceManager.GetString("ResetPassword_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset your password..
        /// </summary>
        public static string ResetPassword_Title2 {
            get {
                return ResourceManager.GetString("ResetPassword_Title2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been reset. Please.
        /// </summary>
        public static string ResetPasswordConfirmation_Message1 {
            get {
                return ResourceManager.GetString("ResetPasswordConfirmation_Message1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to click here to log in.
        /// </summary>
        public static string ResetPasswordConfirmation_Message2 {
            get {
                return ResourceManager.GetString("ResetPasswordConfirmation_Message2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password confirmation.
        /// </summary>
        public static string ResetPasswordConfirmation_Title {
            get {
                return ResourceManager.GetString("ResetPasswordConfirmation_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and.
        /// </summary>
        public static string Text_And {
            get {
                return ResourceManager.GetString("Text_And", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By checking this box, you consent to your personal data being taken in accordance with.
        /// </summary>
        public static string Text_CheckboxConditionUtilisation1 {
            get {
                return ResourceManager.GetString("Text_CheckboxConditionUtilisation1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to our personal data processing conditions.
        /// </summary>
        public static string Text_CheckboxConditionUtilisation2 {
            get {
                return ResourceManager.GetString("Text_CheckboxConditionUtilisation2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string Text_ConfirmPassword {
            get {
                return ResourceManager.GetString("Text_ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        public static string Text_FirstName {
            get {
                return ResourceManager.GetString("Text_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        public static string Text_LastName {
            get {
                return ResourceManager.GetString("Text_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or login.
        /// </summary>
        public static string Text_Link_Login {
            get {
                return ResourceManager.GetString("Text_Link_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or register.
        /// </summary>
        public static string Text_Link_Register {
            get {
                return ResourceManager.GetString("Text_Link_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Text_Login {
            get {
                return ResourceManager.GetString("Text_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        public static string Text_Logout {
            get {
                return ResourceManager.GetString("Text_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string Text_Mail {
            get {
                return ResourceManager.GetString("Text_Mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Text_Name {
            get {
                return ResourceManager.GetString("Text_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or.
        /// </summary>
        public static string Text_Or {
            get {
                return ResourceManager.GetString("Text_Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Text_Password {
            get {
                return ResourceManager.GetString("Text_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Text_Profil {
            get {
                return ResourceManager.GetString("Text_Profil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Text_Register {
            get {
                return ResourceManager.GetString("Text_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me.
        /// </summary>
        public static string Text_Remember {
            get {
                return ResourceManager.GetString("Text_Remember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login wih google.
        /// </summary>
        public static string TextBtnLoginGoogle {
            get {
                return ResourceManager.GetString("TextBtnLoginGoogle", resourceCulture);
            }
        }
    }
}
