global using FluentValidation;
global using MediatR;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.Extensions.Logging;
global using USite.Application.Common.Exceptions;
global using USite.Application.Common.Interfaces;
global using USite.Application.Common.Models;
global using USite.Application.Common.Security;
global using USite.Domain.Entities;