replicaCount: 1

image:
  repository: louthier/frontend-cms-service
  pullPolicy: Always
  tag: "latest"

imagePullSecrets:
  - name: regcred

service:
  type: ClusterIP
  port: 80

ingress:
  className: nginx
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: "/"
  hosts:
    - host: cms.usite.fr
      paths: 
      - path: "/"
        pathType: Prefix


autoscaling:
  enabled: false

PodDisruptionBudget:
  enabled: true
  minAvailable: 1

serviceAccount:
  create: false